[package]
name = "cadmium"
version = "0.1.0"
authors = ["Victor Roest <victor@xirion.net>"]
edition = "2018"

[dependencies]
logind-dbus="0.1.1"
rpassword="4.0.1"
pam="0.7.0"
pam-sys="0.5.6"
nix="0.15.0"
users="0.9.1"
chvt="0.2.0"
rand="0.7.2"
xcb="0.9.0"
